site:
    title: "bluepi0j"
    subtitle: "构建只为纯粹书写的博客"
    limit: 10
    theme: theme
    lang: en
    url: "http://www.bluepi0j.com"
    comment: bluepi0j
    logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "bluepi0j"
        intro: "UofT Computer Science Student, iOS developer"
        avatar: "-/images/avatar.png"

build:
    # output: "public"
    port: 80
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
