site:
    title: "bluepi0j"
    subtitle: ""
    limit: 10
    theme: theme
    lang: en
    url: "http://www.bluepi0j.com/blog/en"
    comment: username
    logo: "-/images/avatar.png"
    link: "{title}.html"
    root: "/blog/en"

authors:
    me:
        name: "bluepi0j"
        intro: "UofT Computer Science Student, iOS developer"
        avatar: "-/images/avatar.png"

build:
    # output: "public"
    port: 80
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
